{
 "title": "Automation Analytics - Usage Metrics",
 "time": { "from": "now-36h", "to": "now-12h" },
 "panels": [
  { "title": "Pendo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latest accounts count for page",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pendo_num_accounts_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Accounts per day for page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pendo_num_accounts_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Latest visitors count for page",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pendo_num_visitors_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Visitors per day for page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pendo_num_visitors_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Latest views count for page",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pendo_num_views_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Views per day for page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pendo_num_views_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Avg Time Per Day For Page",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pendo_avg_time_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  {
   "title": "Average time per day for page",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "pendo_avg_time_per_day_for_page{page_name=~\"_automation analytics .*\"}",
     "legendFormat": "{{page_name}}"
    }
   ]
  },
  { "title": "Top Customer Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Top 10 Customers by upload",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, ta_job_num_uploads_total)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top 5 Customers by cluster count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, max(ta_job_cluster_versions_total) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Tower Cluster Versions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Top 5 Tower Cluster Versions Reporting",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, count(max(ta_job_cluster_versions_total) by (tenant, tower_version)) by (tower_version))",
     "legendFormat": "{{tower_version}}"
    }
   ]
  },
  {
   "title": "Clusters count by Ansible Tower version",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(max(ta_job_cluster_versions_total) by (tenant, tower_version)) by (tower_version)",
     "legendFormat": "{{tower_version}}"
    }
   ]
  },
  { "title": "Customer Uploads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Total Customers Sending Data",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(max(ta_job_cluster_versions_total) by (tenant))",
     "legendFormat": "customers"
    }
   ]
  },
  {
   "title": "Customer Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(max(ta_job_cluster_versions_total) by (tenant))"
    }
   ]
  },
  { "title": "Active Customers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Current active customers with more than 1 host",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(((count(ta_job_cluster_versions_total) by (tenant) * 0 + 1) * on (tenant) (max(ta_job_num_hosts_total) by (tenant))) > 1)"
    }
   ]
  },
  {
   "title": "Active customers with more than 1 host",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(((count(ta_job_cluster_versions_total) by (tenant) * 0 + 1) * on (tenant) (max(ta_job_num_hosts_total) by (tenant))) > 1)",
     "legendFormat": "customers"
    }
   ]
  }
 ]
}