{
 "title": "Automation Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "DatasourceRDS", "label": "DatasourceRDS", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "tower-analytics-stage,tower-analytics-prod"
   },
   { "name": "granularity", "query": "daily,monthly,yearly" },
   {
    "name": "realtime_rollup_series",
    "query": "ta_rollup_processor_rollup_event_explorer_rollup_time_bucket,ta_rollup_processor_rollup_host_event_explorer_rollup_time_bucket,ta_rollup_processor_rollup_host_explorer_rollup_time_bucket,ta_rollup_processor_rollup_job_explorer_rollup_failed_steps_time_bucket,ta_rollup_processor_rollup_job_explorer_rollup_jobs_time_bucket,ta_rollup_processor_rollup_job_explorer_rollup_workflow_hierarchy_time_bucket,ta_rollup_processor_rollup_job_explorer_rollup_workflows_time_bucket"
   },
   {
    "name": "granularity_rollups",
    "query": "job_explorer,event_explorer,host_explorer"
   },
   {
    "name": "processor_tables",
    "query": "analytics_bundle,events_table,unified_jobs"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{namespace=\"$namespace\"}",
     "legendFormat": "{{service}}, pod: {{pod}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Ingress received payloads per day [code = 202]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[1d]))",
     "legendFormat": "Successful ingress uploads per day"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code != 202] by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[1d])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per minute [code = 202]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[$__interval])*60)",
     "legendFormat": "Successful ingress uploads per minute"
    }
   ]
  },
  {
   "title": "Ingress received payloads per minute [code != 202] by code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[$__interval])*60) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code = 202] by client",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code=\"202\"}[1d])) by (useragent, code)",
     "legendFormat": "{{useragent}}"
    }
   ]
  },
  {
   "title": "Ingress received payloads per day [code != 202] by client and code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ingress_responses{useragent=~\"(Red Hat Ansible Tower.*)|(python-requests.*)|(AWX.*)\", code!=\"202\"}[1d])) by (useragent, code)",
     "legendFormat": "code: {{code}}, agent: {{useragent}}"
    }
   ]
  },
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Processor processing rate per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ta_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Processed payloads past day"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "CPU usage: {{ pod }}"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "CPU request"
    },
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-processor.*\", namespace=~\"$namespace\"}[5m])) \nby (pod)",
     "legendFormat": "CPU throttled: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor processed bytes per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Transmit total"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Receive total"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-processor.*\"})",
     "legendFormat": "Memory limit: {{ container }}"
    },
    {
     "expr": "sum((container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"automation-analytics-processor.*\", pod=~\"automation-analytics-processor.*\"})) by (pod)",
     "legendFormat": "Usage bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor processing rate per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ta_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[$__interval])*60) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "Transmit bytes: {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])) by (pod)",
     "legendFormat": "Receive bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Processor exception per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ta_processor_exception_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[1d]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(increase(ta_processor_processing_time_v2_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processor exception per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ta_processor_exception_total{namespace=~\"$namespace\", pod=~\"automation-analytics-processor.*\"}[5m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing time last 7 days",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_processor_processing_time_v2_bucket{pod=~\"automation-analytics-processor.*\"}[7d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processor Kafka lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_group_lag {topic=\"platform.upload.tower\", group=~\"processor|processor-stage\"}) by (partition)",
     "legendFormat": "Partition: {{ partition}}"
    }
   ]
  },
  {
   "title": "Processor detail timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time of ${processor_tables}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
     "repeat": "processor_tables",
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 13 },
     "repeat": "processor_tables",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 13 },
     "repeat": "processor_tables",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 13 },
     "repeat": "processor_tables",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of ${processor_tables}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time of ${processor_tables}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_processor_handle_${processor_tables}_bucket{pod=~\"automation-analytics-processor.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Rollups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Rollup processor processing rate per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_whole_rollup_job_processing_time_count{namespace=~\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[1d]))"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-rollups.*\"})",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[5m])) by (pod)",
     "legendFormat": "CPU usage: {{ pod }}"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-rollups.*\"})",
     "legendFormat": "CPU request"
    },
    {
     "expr": "sum(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-rollups.*\", namespace=~\"$namespace\"}[5m])) \nby (pod)",
     "legendFormat": "CPU throttled: {{ pod }}"
    }
   ]
  },
  {
   "title": "Rollup processor processing rate per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(ta_rollup_processor_message_processed_total{namespace=~\"$namespace\", pod=~\"automation-analytics-rollups-.*\"}[$__interval])*60) by (pod)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-rollups.*\"})",
     "legendFormat": "Memory limit: {{ container }}"
    },
    {
     "expr": "sum((container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"automation-analytics-rollups.*\", pod=~\"automation-analytics-rollups.*\"})) by (pod)",
     "legendFormat": "Usage bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Network usage per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[1d]))",
     "legendFormat": "Transmit total"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[1d]))",
     "legendFormat": "Receive total"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[5m])) by (pod)",
     "legendFormat": "Transmit bytes: {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-rollups.*\"}[5m])) by (pod)",
     "legendFormat": "Receive bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Rollup processor exception per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ta_rollup_processor_exception_total{namespace=~\"$namespace\", pod=~\"automation-analytics-rollups-.*\"}[5m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Processing time of rollups and running rules [last 7d]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_whole_rollup_job_processing_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_whole_rollup_job_processing_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time of rollup batch (max 2 months) [last 7d]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_rollup_processing_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time of rollup batch (max 2 months) ",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_rollup_processing_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time of running rules [last 7d]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_run_rules_processing_time_bucket{pod=~\"automation-analytics-rollups.*\"}[7d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time of running rules",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 155 },
   "targets": [
    {
     "expr": "sum(increase(ta_rollup_processor_run_rules_processing_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rollups detail timings [realtime]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 15 },
     "repeat": "realtime_rollup_series",
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 15 },
     "repeat": "realtime_rollup_series",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 15 },
     "repeat": "realtime_rollup_series",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 15 },
     "repeat": "realtime_rollup_series",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time ${realtime_rollup_series}",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 16, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 4, "x": 20, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(${realtime_rollup_series}{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollups detail timings [$granularity]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "repeat": "granularity",
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "repeat": "granularity_rollups",
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollups detail timings [$granularity]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "repeat": "granularity_rollups",
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rollups detail timings [$granularity]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 170 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "repeat": "granularity_rollups",
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 16 },
     "repeat": "granularity_rollups",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups}",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[1h])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: $granularity ${granularity_rollups} [last 30 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[30d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 7 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time: ${granularity} ${granularity_rollups} [last 2 days]",
     "type": "bargauge",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_rollup_processor_rollup_${granularity}_${granularity_rollups}_rollup_time_bucket{pod=~\"automation-analytics-rollups-.*\"}[2d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Migrations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processing time",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "sum(increase(ta_migrations_migration_processing_time_bucket[1m])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Processing time last 7 days",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(increase(ta_migrations_migration_processing_time_bucket[7d])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 172 } },
  {
   "title": "Requests per day, by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"tower-analytics\"}[1d])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 173 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "CPU limit"
    },
    {
     "expr": "max by (container) (kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "CPU request"
    },
    {
     "expr": "max(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m]))",
     "legendFormat": "MAX CPU usage"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", namespace=~\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m]))",
     "legendFormat": "AVG CPU usage"
    },
    {
     "expr": "max(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-api-fastapi.*\", namespace=~\"$namespace\"}[5m])) \n",
     "legendFormat": "MAX CPU throttled"
    },
    {
     "expr": "avg(\n    rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", image!=\"\", pod=~\"automation-analytics-api-fastapi.*\", namespace=~\"$namespace\"}[5m])) ",
     "legendFormat": "AVG CPU throttled"
    }
   ]
  },
  {
   "title": "Requests per minute, by status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(api_3scale_gateway_api_status{exported_service=\"tower-analytics\"}[5m])*60) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (container) (kube_pod_container_resource_limits_memory_bytes{namespace=~\"$namespace\", container=~\"automation-analytics-api-fastapi.*\"})",
     "legendFormat": "Memory limit: {{ container }}"
    },
    {
     "expr": "sum((container_memory_usage_bytes{namespace=\"$namespace\", container=~\"automation-analytics-api-fastapi.*\", pod=~\"automation-analytics-api-fastapi.*\"})) by (pod)",
     "legendFormat": "Usage bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Network per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[1d]))",
     "legendFormat": "Transmit total"
    },
    {
     "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[1d]))",
     "legendFormat": "Receive total"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m])) by (pod)",
     "legendFormat": "Transmit bytes: {{ pod }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"automation-analytics-api-fastapi.*\"}[5m])) by (pod)",
     "legendFormat": "Receive bytes: {{ pod }}"
    }
   ]
  },
  {
   "title": "Requests per day by view ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path_template) (increase(ta_api_requests_total{namespace=\"$namespace\"}[1d]))",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Request Latency Rate by View",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 200 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rate(ta_api_requests_processing_time_seconds_sum[5m]) / rate(ta_api_requests_processing_time_seconds_count[5m])) by (path_template)",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Requests per minute by view ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (path_template) (rate(ta_api_requests_total{namespace=\"$namespace\", path_template!=\"/metrics\"}[30m])*60)",
     "legendFormat": "{{path_template}}"
    }
   ]
  },
  {
   "title": "Errors by path and tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 208 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ta_api_responses_total{namespace=\"$namespace\", status_code=\"500\"}) by (path_template, tenant)",
     "legendFormat": "{{path_template}} - {{tenant}}"
    }
   ]
  },
  {
   "title": "Total request Errors per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 216 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_3scale_gateway_api_status{exported_service=\"tower-analytics\",status=\"5xx\"}[1d]))",
     "legendFormat": "5xx errors (3scale)"
    },
    {
     "expr": "sum(increase(ta_api_responses_total{namespace=\"$namespace\",status_code=~\"5..\"}[1d]))",
     "legendFormat": "5.. errors (analytics app)"
    }
   ]
  },
  {
   "title": "Request Errors per day by view",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 225 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ta_api_responses_total{namespace=\"$namespace\",status_code=~\"5..\"}[1d])) by (status_code, path_template)",
     "legendFormat": "{{status_code}} {{path_template}}"
    }
   ]
  },
  { "title": "RDS Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 234 } },
  {
   "title": "RDS database connections average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_rds_database_connections_average{dbinstance_identifier=\"$namespace\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "RDS CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 235 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(aws_rds_cpuutilization_average{dbinstance_identifier=\"$namespace\"})",
     "legendFormat": "CPU utilization average"
    },
    {
     "expr": "sum(rdsosmetrics_cpuUtilization_total{exported_instance=\"$namespace\"})",
     "legendFormat": "OS Metrics Total Util"
    },
    {
     "expr": "sum(rdsosmetrics_cpuUtilization_system{exported_instance=\"$namespace\"})",
     "legendFormat": "OS Metrics System Util"
    }
   ]
  },
  {
   "title": "RDS storage space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 243 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_fileSys_total{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
     "legendFormat": "Storage total "
    },
    {
     "expr": "max(rdsosmetrics_fileSys_used{exported_instance=\"$namespace\", mount_point=\"/rdsdbdata\"})",
     "legendFormat": "Storage used"
    }
   ]
  },
  {
   "title": "RDS memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 243 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_memory_total{exported_instance=\"$namespace\"})",
     "legendFormat": "Memory total"
    },
    {
     "expr": "max(rdsosmetrics_memory_free{exported_instance=\"$namespace\"})",
     "legendFormat": "Memory free"
    },
    {
     "expr": "max(rdsosmetrics_memory_cached{exported_instance=\"$namespace\"})",
     "legendFormat": "Memory cached"
    },
    {
     "expr": "max(rdsosmetrics_memory_buffers{exported_instance=\"$namespace\"})",
     "legendFormat": "Memory buffers"
    },
    {
     "expr": "max(rdsosmetrics_memory_active{exported_instance=\"$namespace\"})",
     "legendFormat": "Memory active"
    }
   ]
  },
  {
   "title": "RDS tasks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_tasks_sleeping{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks sleeping"
    },
    {
     "expr": "max(rdsosmetrics_tasks_running{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks running"
    },
    {
     "expr": "max(rdsosmetrics_tasks_blocked{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks blocked"
    },
    {
     "expr": "max(rdsosmetrics_tasks_stopped{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks stopped"
    },
    {
     "expr": "max(rdsosmetrics_tasks_total{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks total"
    },
    {
     "expr": "max(rdsosmetrics_tasks_zombie{exported_instance=\"$namespace\"})",
     "legendFormat": "Tasks zombie"
    }
   ]
  },
  {
   "title": "RDS DIsk IO util",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 251 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_diskIO_util{exported_instance=\"$namespace\"}) by (device)",
     "legendFormat": "Device: {{device}}"
    }
   ]
  },
  {
   "title": "Timestamp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 259 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_timestamp{exported_instance=\"$namespace\"})",
     "legendFormat": "Timestamp"
    }
   ]
  },
  {
   "title": "RDS network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 259 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "max(rdsosmetrics_network_rx{exported_instance=\"$namespace\"})",
     "legendFormat": "Network receive"
    },
    {
     "expr": "max(rdsosmetrics_network_tx{exported_instance=\"$namespace\"})",
     "legendFormat": "Network transmit"
    }
   ]
  },
  {
   "title": "RDS latency average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 267 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(aws_rds_read_latency_average{dbinstance_identifier=\"$namespace\"})",
     "legendFormat": "Read Latency Average"
    },
    {
     "expr": "max(aws_rds_write_latency_average{dbinstance_identifier=\"$namespace\"})",
     "legendFormat": "Write Latency Average"
    }
   ]
  },
  { "title": "Internal statistics cron", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 } },
  {
   "title": "Processing time of tenant internal stats",
   "type": "heatmap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 276 },
   "targets": [
    {
     "expr": "sum(increase(ta_job_tenant_metrics_processing_time_bucket[1h])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time: [last 30 days]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 12, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_job_tenant_metrics_processing_time_bucket[30d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time: [last 7 days]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 16, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_job_tenant_metrics_processing_time_bucket[7d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Processing time: [last 2 days]",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(ta_job_tenant_metrics_processing_time_bucket[2d])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}